ANGLE: true
COS: false
D: 3
MSE: false
NORM: true
ORTHO: false
batch_size: 100000
dpath: /eos/home-p/phzehetn/Data/NewCov/
epochs: 10000
identifier: AngleNorm_medium3D
n: 1000000
nodes:
- 128
- 64
- 32
- 16
- 32
- 64
- 128
slim: false
